#!/usr/bin/env bash
# Vendor Cargo crates (+ npm deps for the Tauri log viewer) for offline PPA builds.
# Output (not committed to git — packed into the orig tarball by make-orig.sh):
#   cargo-vendor/<name>/
#   npm-vendor/logs-node_modules.tar.xz
set -euo pipefail

ROOT="$(cd "${1:-$(dirname "${BASH_SOURCE[0]}")/../..}" && pwd)"
cd "$ROOT"

if ! command -v cargo >/dev/null 2>&1; then
	echo "vendor-all: cargo not found (install Ubuntu package 'cargo')" >&2
	exit 1
fi
if ! command -v npm >/dev/null 2>&1; then
	echo "vendor-all: npm not found (install Ubuntu package 'npm')" >&2
	exit 1
fi

VENDOR_ROOT="$ROOT/cargo-vendor"
NPM_VENDOR="$ROOT/npm-vendor"
rm -rf "$VENDOR_ROOT" "$NPM_VENDOR"
mkdir -p "$VENDOR_ROOT" "$NPM_VENDOR"

# name|relative path of crate/workspace that owns Cargo.lock
PROJECTS=(
	"compositor|compositor.kernel/kernel.loader"
	"polkit|compositor.installer/component/pollkit-agent"
	"mx|compositor.installer/component/mx-gesture-daemon"
	"xwayland|compositor.installer/component/xwayland-satellite/xwayland-fixes"
	"settings|compositor.installer/component/settings-editor"
	"tauri|compositor.developer/developer.tool/developer.tool.window/logs/src-tauri"
)

vendor_one() {
	local name="$1" rel="$2"
	local proj="$ROOT/$rel"
	local dest="$VENDOR_ROOT/$name"
	[ -f "$proj/Cargo.lock" ] || { echo "vendor-all: missing Cargo.lock in $rel" >&2; exit 1; }
	echo ">> cargo vendor [$name] from $rel" >&2
	mkdir -p "$dest"
	(
		cd "$proj"
		if ! cargo metadata --format-version 1 --locked >/dev/null 2>&1; then
			echo "vendor-all: Cargo.lock in $rel is stale (does not match its manifest)." >&2
			echo "vendor-all: run 'cargo update' there, review and COMMIT the lockfile diff," >&2
			echo "vendor-all: then re-run. Refusing to regenerate lockfiles during packaging." >&2
			exit 1
		fi
		# stdout is the config fragment; write crates into $dest
		cargo vendor --locked "$dest" >"$VENDOR_ROOT/$name.config.toml"
	)
}

for entry in "${PROJECTS[@]}"; do
	name="${entry%%|*}"
	rel="${entry#*|}"
	vendor_one "$name" "$rel"
done

LOGS_DIR="$ROOT/compositor.developer/developer.tool/developer.tool.window/logs"
echo ">> npm ci (Tauri frontend) in $LOGS_DIR" >&2
(
	cd "$LOGS_DIR"
	rm -rf node_modules
	npm ci --ignore-scripts
	tar -cJf "$NPM_VENDOR/logs-node_modules.tar.xz" node_modules
	rm -rf node_modules
)

# Record manifest for README.source / debugging.
{
	echo "# Generated by debian/scripts/vendor-all.sh"
	echo "date: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
	echo "cargo: $(cargo --version)"
	echo "rustc: $(rustc --version 2>/dev/null || echo missing)"
	echo "npm: $(npm --version)"
	for entry in "${PROJECTS[@]}"; do
		name="${entry%%|*}"
		echo "cargo-vendor/$name"
	done
	echo "npm-vendor/logs-node_modules.tar.xz"
} >"$VENDOR_ROOT/MANIFEST.txt"

echo "vendor-all: done → $VENDOR_ROOT and $NPM_VENDOR" >&2
